//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceGame.Models
{
    using System;
    using System.Collections.Generic;

    public partial class DesignedGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DesignedGame()
        {
            this.Comments = new List<GameComment>();
            this.WaitedGame = new List<int>();
        }

        public int Id { get; set; }
        public string DesignerUser { get; set; }
        public int CountPlayed { get; set; }
        public int TotalScore { get; set; }
        public int AverageScore { get; set; }
        public int MaxScore { get; set; }
        public int CurrentScore { get; set; }
        public int DiceCount { get; set; }
        public string DateBuild { get; set; }
        public int MaxPartab { get; set; }
        public IList<GameComment> Comments { get; set; }
        public IList<int> WaitedGame { get; set; }

    }
}
