//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceGame.Models
{
    using System;
    using System.Collections.Generic;

    public partial class UserComment { 
         public UserComment()
        {

        }
        public int Id { get; set; }
        public string CommenterUser { get; set; }
        public string User { get; set; }
        public String Comment { get; set; }
        public string date { get; set; }
        public int flag { get; set; }


    }
}
